name=ESP32 BLE Keyboard
version=0.4.0
author=T-vK, Sakul_the_one
maintainer=Sakul_the_one
sentence=Sakuls Bluetooth LE Keyboard library for the ESP32.
paragraph=Sakuls Bluetooth LE Keyboard library for the ESP32.
category=Communication
url=https://github.com/sakul-the-one/sakuls-ESP32-BLE-Keyboard
architectures=esp32
